project_id = "kusgjgstdabonfntxwsq"

[functions.send-report-notification]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.check-email-exists]
verify_jwt = true

[functions.send-feedback-request]
verify_jwt = true

[functions.send-feedback-reminder]
verify_jwt = true

[functions.auto-send-feedback]
verify_jwt = false

