// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kusgjgstdabonfntxwsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1c2dqZ3N0ZGFib25mbnR4d3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MzMzMDYsImV4cCI6MjA3NjAwOTMwNn0.tAp4Ug1O2yutOfFHtNWEBkzSyVJHJJ3z0kJSE1J9-nA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});